// <auto-generated />
using Ghana.Services.PopulationAPI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ghana.Services.PopulationAPI.Migrations
{
    [DbContext(typeof(PopulationContext))]
    [Migration("20211201130637_AddPopulationModel")]
    partial class AddPopulationModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ghana.Services.PopulationAPI.Models.Population", b =>
                {
                    b.Property<string>("DivisionCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Citizens")
                        .HasColumnType("int");

                    b.Property<int>("ElderlyFemale")
                        .HasColumnType("int");

                    b.Property<int>("ElderlyMale")
                        .HasColumnType("int");

                    b.Property<int>("Female")
                        .HasColumnType("int");

                    b.Property<int>("Male")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("DivisionCode");

                    b.ToTable("Population");
                });
#pragma warning restore 612, 618
        }
    }
}
